module Subs

  class Language

    attr_reader :name
    attr_reader :iso639_1
    attr_reader :iso639_2

    def initialize(name, two_digit, three_digit, upload, web)
      @name = name
      @iso639_1 = two_digit
      @iso639_2 = three_digit
      @upload_enabled = upload
      @web_enabled = web
    end

    def web_enabled?
      @web_enabled
    end

    def upload_enabled?
      @upload_enabled
    end

    def to_s
      "#{@name} (#{@iso639_2})"
    end

    def self.from_iso639_1(code)
      code = code.downcase
      values.find { |lang| lang.iso639_1 == code }
    end

    def self.from_iso639_2(code)
      code = code.downcase
      values.find { |lang| lang.iso639_2 == code }
    end

    def self.from_name(name)
      values.find_all { |lang| lang.name.include?(name) }
    end

    def self.default

    end

    def self.values
      @values ||= [
          Language.new("Afar, afar", 'aa', 'aar', false, false),
          Language.new("Abkhazian", 'ab', 'abk', false, false),
          Language.new("Achinese", nil, 'ace', false, false),
          Language.new("Acoli", nil, 'ach', false, false),
          Language.new("Adangme", nil, 'ada', false, false),
          Language.new("adyghé", nil, 'ady', false, false),
          Language.new("Afro-Asiatic (Other)", nil, 'afa', false, false),
          Language.new("Afrihili", nil, 'afh', false, false),
          Language.new("Afrikaans", 'af', 'afr', true, false),
          Language.new("Ainu", nil, 'ain', false, false),
          Language.new("Akan", 'ak', 'aka', false, false),
          Language.new("Akkadian", nil, 'akk', false, false),
          Language.new("Albanian", 'sq', 'alb', true, true),
          Language.new("Aleut", nil, 'ale', false, false),
          Language.new("Algonquian languages", nil, 'alg', false, false),
          Language.new("Southern Altai", nil, 'alt', false, false),
          Language.new("Amharic", 'am', 'amh', false, false),
          Language.new("English, Old (ca.450-1100)", nil, 'ang', false, false),
          Language.new("Apache languages", nil, 'apa', false, false),
          Language.new("Arabic", 'ar', 'ara', true, true),
          Language.new("Aramaic", nil, 'arc', false, false),
          Language.new("Aragonese", 'an', 'arg', true, true),
          Language.new("Armenian", 'hy', 'arm', true, true),
          Language.new("Araucanian", nil, 'arn', false, false),
          Language.new("Arapaho", nil, 'arp', false, false),
          Language.new("Artificial (Other)", nil, 'art', false, false),
          Language.new("Arawak", nil, 'arw', false, false),
          Language.new("Assamese", 'as', 'asm', false, false),
          Language.new("Asturian", 'at', 'ast', true, true),
          Language.new("Athapascan languages", nil, 'ath', false, false),
          Language.new("Australian languages", nil, 'aus', false, false),
          Language.new("Avaric", 'av', 'ava', false, false),
          Language.new("Avestan", 'ae', 'ave', false, false),
          Language.new("Awadhi", nil, 'awa', false, false),
          Language.new("Aymara", 'ay', 'aym', false, false),
          Language.new("Azerbaijani", 'az', 'aze', true, false),
          Language.new("Banda", nil, 'bad', false, false),
          Language.new("Bamileke languages", nil, 'bai', false, false),
          Language.new("Bashkir", 'ba', 'bak', false, false),
          Language.new("Baluchi", nil, 'bal', false, false),
          Language.new("Bambara", 'bm', 'bam', false, false),
          Language.new("Balinese", nil, 'ban', false, false),
          Language.new("Basque", 'eu', 'baq', true, true),
          Language.new("Basa", nil, 'bas', false, false),
          Language.new("Baltic (Other)", nil, 'bat', false, false),
          Language.new("Beja", nil, 'bej', false, false),
          Language.new("Belarusian", 'be', 'bel', true, false),
          Language.new("Bemba", nil, 'bem', false, false),
          Language.new("Bengali", 'bn', 'ben', true, false),
          Language.new("Berber (Other)", nil, 'ber', false, false),
          Language.new("Bhojpuri", nil, 'bho', false, false),
          Language.new("Bihari", 'bh', 'bih', false, false),
          Language.new("Bikol", nil, 'bik', false, false),
          Language.new("Bini", nil, 'bin', false, false),
          Language.new("Bislama", 'bi', 'bis', false, false),
          Language.new("Siksika", nil, 'bla', false, false),
          Language.new("Bantu (Other)", nil, 'bnt', false, false),
          Language.new("Bosnian", 'bs', 'bos', true, false),
          Language.new("Braj", nil, 'bra', false, false),
          Language.new("Breton", 'br', 'bre', true, true),
          Language.new("Batak (Indonesia)", nil, 'btk', false, false),
          Language.new("Buriat", nil, 'bua', false, false),
          Language.new("Buginese", nil, 'bug', false, false),
          Language.new("Bulgarian", 'bg', 'bul', true, true),
          Language.new("Burmese", 'my', 'bur', true, false),
          Language.new("Blin", nil, 'byn', false, false),
          Language.new("Caddo", nil, 'cad', false, false),
          Language.new("Central American Indian (Other)", nil, 'cai', false, false),
          Language.new("Carib", nil, 'car', false, false),
          Language.new("Catalan", 'ca', 'cat', true, true),
          Language.new("Caucasian (Other)", nil, 'cau', false, false),
          Language.new("Cebuano", nil, 'ceb', false, false),
          Language.new("Celtic (Other)", nil, 'cel', false, false),
          Language.new("Chamorro", 'ch', 'cha', false, false),
          Language.new("Chibcha", nil, 'chb', false, false),
          Language.new("Chechen", 'ce', 'che', false, false),
          Language.new("Chagatai", nil, 'chg', false, false),
          Language.new("Chinese (simplified)", 'zh', 'chi', true, true),
          Language.new("Chuukese", nil, 'chk', false, false),
          Language.new("Mari", nil, 'chm', false, false),
          Language.new("Chinook jargon", nil, 'chn', false, false),
          Language.new("Choctaw", nil, 'cho', false, false),
          Language.new("Chipewyan", nil, 'chp', false, false),
          Language.new("Cherokee", nil, 'chr', false, false),
          Language.new("Church Slavic", 'cu', 'chu', false, false),
          Language.new("Chuvash", 'cv', 'chv', false, false),
          Language.new("Cheyenne", nil, 'chy', false, false),
          Language.new("Chamic languages", nil, 'cmc', false, false),
          Language.new("Coptic", nil, 'cop', false, false),
          Language.new("Cornish", 'kw', 'cor', false, false),
          Language.new("Corsican", 'co', 'cos', false, false),
          Language.new("Creoles and pidgins, English based (Other)", nil, 'cpe', false, false),
          Language.new("Creoles and pidgins, French-based (Other)", nil, 'cpf', false, false),
          Language.new("Creoles and pidgins, Portuguese-based (Other)", nil, 'cpp', false, false),
          Language.new("Cree", 'cr', 'cre', false, false),
          Language.new("Crimean Tatar", nil, 'crh', false, false),
          Language.new("Creoles and pidgins (Other)", nil, 'crp', false, false),
          Language.new("Kashubian", nil, 'csb', false, false),
          Language.new("Cushitic (Other)' couchitiques, autres langues", nil, 'cus', false, false),
          Language.new("Czech", 'cs', 'cze', true, true),
          Language.new("Dakota", nil, 'dak', false, false),
          Language.new("Danish", 'da', 'dan', true, true),
          Language.new("Dargwa", nil, 'dar', false, false),
          Language.new("Dayak", nil, 'day', false, false),
          Language.new("Delaware", nil, 'del', false, false),
          Language.new("Slave (Athapascan)", nil, 'den', false, false),
          Language.new("Dogrib", nil, 'dgr', false, false),
          Language.new("Dinka", nil, 'din', false, false),
          Language.new("Divehi", 'dv', 'div', false, false),
          Language.new("Dogri", nil, 'doi', false, false),
          Language.new("Dravidian (Other)", nil, 'dra', false, false),
          Language.new("Duala", nil, 'dua', false, false),
          Language.new("Dutch, Middle (ca.1050-1350)", nil, 'dum', false, false),
          Language.new("Dutch", 'nl', 'dut', true, true),
          Language.new("Dyula", nil, 'dyu', false, false),
          Language.new("Dzongkha", 'dz', 'dzo', false, false),
          Language.new("Efik", nil, 'efi', false, false),
          Language.new("Egyptian (Ancient)", nil, 'egy', false, false),
          Language.new("Ekajuk", nil, 'eka', false, false),
          Language.new("Elamite", nil, 'elx', false, false),
          Language.new("English", 'en', 'eng', true, true),
          Language.new("English, Middle (1100-1500)", nil, 'enm', false, false),
          Language.new("Esperanto", 'eo', 'epo', true, true),
          Language.new("Estonian", 'et', 'est', true, true),
          Language.new("Ewe", 'ee', 'ewe', false, false),
          Language.new("Ewondo", nil, 'ewo', false, false),
          Language.new("Fang", nil, 'fan', false, false),
          Language.new("Faroese", 'fo', 'fao', false, false),
          Language.new("Fanti", nil, 'fat', false, false),
          Language.new("Fijian", 'fj', 'fij', false, false),
          Language.new("Filipino", nil, 'fil', false, false),
          Language.new("Finnish", 'fi', 'fin', true, true),
          Language.new("Finno-Ugrian (Other)", nil, 'fiu', false, false),
          Language.new("Fon", nil, 'fon', false, false),
          Language.new("French", 'fr', 'fre', true, true),
          Language.new("French, Middle (ca.1400-1600)", nil, 'frm', false, false),
          Language.new("French, Old (842-ca.1400)", nil, 'fro', false, false),
          Language.new("Frisian", 'fy', 'fry', false, false),
          Language.new("Fulah", 'ff', 'ful', false, false),
          Language.new("Friulian", nil, 'fur', false, false),
          Language.new("Ga", nil, 'gaa', false, false),
          Language.new("Gayo", nil, 'gay', false, false),
          Language.new("Gbaya", nil, 'gba', false, false),
          Language.new("Germanic (Other)", nil, 'gem', false, false),
          Language.new("Georgian", 'ka', 'geo', true, true),
          Language.new("German", 'de', 'ger', true, true),
          Language.new("Geez", nil, 'gez', false, false),
          Language.new("Gilbertese", nil, 'gil', false, false),
          Language.new("Gaelic", 'gd', 'gla', true, false),
          Language.new("Irish", 'ga', 'gle', true, false),
          Language.new("Galician", 'gl', 'glg', true, true),
          Language.new("Manx", 'gv', 'glv', false, false),
          Language.new("German, Middle High (ca.1050-1500)", nil, 'gmh', false, false),
          Language.new("German, Old High (ca.750-1050)", nil, 'goh', false, false),
          Language.new("Gondi", nil, 'gon', false, false),
          Language.new("Gorontalo", nil, 'gor', false, false),
          Language.new("Gothic", nil, 'got', false, false),
          Language.new("Grebo", nil, 'grb', false, false),
          Language.new("Greek, Ancient (to 1453)", nil, 'grc', false, false),
          Language.new("Greek", 'el', 'ell', true, true),
          Language.new("Guarani", 'gn', 'grn', false, false),
          Language.new("Gujarati", 'gu', 'guj', false, false),
          Language.new("Gwich´in", nil, 'gwi', false, false),
          Language.new("Haida", nil, 'hai', false, false),
          Language.new("Haitian", 'ht', 'hat', false, false),
          Language.new("Hausa", 'ha', 'hau', false, false),
          Language.new("Hawaiian", nil, 'haw', false, false),
          Language.new("Hebrew", 'he', 'heb', true, true),
          Language.new("Herero", 'hz', 'her', false, false),
          Language.new("Hiligaynon", nil, 'hil', false, false),
          Language.new("Himachali", nil, 'him', false, false),
          Language.new("Hindi", 'hi', 'hin', true, true),
          Language.new("Hittite", nil, 'hit', false, false),
          Language.new("Hmong", nil, 'hmn', false, false),
          Language.new("Hiri Motu", 'ho', 'hmo', false, false),
          Language.new("Croatian", 'hr', 'hrv', true, true),
          Language.new("Hungarian", 'hu', 'hun', true, true),
          Language.new("Hupa", nil, 'hup', false, false),
          Language.new("Iban", nil, 'iba', false, false),
          Language.new("Igbo", 'ig', 'ibo', false, false),
          Language.new("Icelandic", 'is', 'ice', true, true),
          Language.new("Ido", 'io', 'ido', false, false),
          Language.new("Sichuan Yi", 'ii', 'iii', false, false),
          Language.new("Ijo", nil, 'ijo', false, false),
          Language.new("Inuktitut", 'iu', 'iku', false, false),
          Language.new("Interlingue", 'ie', 'ile', false, false),
          Language.new("Iloko", nil, 'ilo', false, false),
          Language.new("Interlingua (International Auxiliary Language Asso", 'ia', 'ina', false, false),
          Language.new("Indic (Other)", nil, 'inc', false, false),
          Language.new("Indonesian", 'id', 'ind', true, true),
          Language.new("Indo-European (Other)", nil, 'ine', false, false),
          Language.new("Ingush", nil, 'inh', false, false),
          Language.new("Inupiaq", 'ik', 'ipk', false, false),
          Language.new("Iranian (Other)", nil, 'ira', false, false),
          Language.new("Iroquoian languages", nil, 'iro', false, false),
          Language.new("Italian", 'it', 'ita', true, true),
          Language.new("Javanese", 'jv', 'jav', false, false),
          Language.new("Japanese", 'ja', 'jpn', true, true),
          Language.new("Judeo-Persian", nil, 'jpr', false, false),
          Language.new("Judeo-Arabic", nil, 'jrb', false, false),
          Language.new("Kara-Kalpak", nil, 'kaa', false, false),
          Language.new("Kabyle", nil, 'kab', false, false),
          Language.new("Kachin", nil, 'kac', false, false),
          Language.new("Kalaallisut", 'kl', 'kal', false, false),
          Language.new("Kamba", nil, 'kam', false, false),
          Language.new("Kannada", 'kn', 'kan', true, false),
          Language.new("Karen", nil, 'kar', false, false),
          Language.new("Kashmiri", 'ks', 'kas', false, false),
          Language.new("Kanuri", 'kr', 'kau', false, false),
          Language.new("Kawi", nil, 'kaw', false, false),
          Language.new("Kazakh", 'kk', 'kaz', true, false),
          Language.new("Kabardian", nil, 'kbd', false, false),
          Language.new("Khasi", nil, 'kha', false, false),
          Language.new("Khoisan (Other)", nil, 'khi', false, false),
          Language.new("Khmer", 'km', 'khm', true, true),
          Language.new("Khotanese", nil, 'kho', false, false),
          Language.new("Kikuyu", 'ki', 'kik', false, false),
          Language.new("Kinyarwanda", 'rw', 'kin', false, false),
          Language.new("Kirghiz", 'ky', 'kir', false, false),
          Language.new("Kimbundu", nil, 'kmb', false, false),
          Language.new("Konkani", nil, 'kok', false, false),
          Language.new("Komi", 'kv', 'kom', false, false),
          Language.new("Kongo", 'kg', 'kon', false, false),
          Language.new("Korean", 'ko', 'kor', true, true),
          Language.new("Kosraean", nil, 'kos', false, false),
          Language.new("Kpelle", nil, 'kpe', false, false),
          Language.new("Karachay-Balkar", nil, 'krc', false, false),
          Language.new("Kru", nil, 'kro', false, false),
          Language.new("Kurukh", nil, 'kru', false, false),
          Language.new("Kuanyama", 'kj', 'kua', false, false),
          Language.new("Kumyk", nil, 'kum', false, false),
          Language.new("Kurdish", 'ku', 'kur', true, false),
          Language.new("Kutenai", nil, 'kut', false, false),
          Language.new("Ladino", nil, 'lad', false, false),
          Language.new("Lahnda", nil, 'lah', false, false),
          Language.new("Lamba", nil, 'lam', false, false),
          Language.new("Lao", 'lo', 'lao', false, false),
          Language.new("Latin", 'la', 'lat', false, false),
          Language.new("Latvian", 'lv', 'lav', true, false),
          Language.new("Lezghian", nil, 'lez', false, false),
          Language.new("Limburgan", 'li', 'lim', false, false),
          Language.new("Lingala", 'ln', 'lin', false, false),
          Language.new("Lithuanian", 'lt', 'lit', true, false),
          Language.new("Mongo", nil, 'lol', false, false),
          Language.new("Lozi", nil, 'loz', false, false),
          Language.new("Luxembourgish", 'lb', 'ltz', true, false),
          Language.new("Luba-Lulua", nil, 'lua', false, false),
          Language.new("Luba-Katanga", 'lu', 'lub', false, false),
          Language.new("Ganda", 'lg', 'lug', false, false),
          Language.new("Luiseno", nil, 'lui', false, false),
          Language.new("Lunda", nil, 'lun', false, false),
          Language.new("Luo (Kenya and Tanzania)", nil, 'luo', false, false),
          Language.new("lushai", nil, 'lus', false, false),
          Language.new("Macedonian", 'mk', 'mac', true, true),
          Language.new("Madurese", nil, 'mad', false, false),
          Language.new("Magahi", nil, 'mag', false, false),
          Language.new("Marshallese", 'mh', 'mah', false, false),
          Language.new("Maithili", nil, 'mai', false, false),
          Language.new("Makasar", nil, 'mak', false, false),
          Language.new("Malayalam", 'ml', 'mal', true, false),
          Language.new("Mandingo", nil, 'man', false, false),
          Language.new("Maori", 'mi', 'mao', false, false),
          Language.new("Austronesian (Other)", nil, 'map', false, false),
          Language.new("Marathi", 'mr', 'mar', false, false),
          Language.new("Masai", nil, 'mas', false, false),
          Language.new("Malay", 'ms', 'may', true, true),
          Language.new("Moksha", nil, 'mdf', false, false),
          Language.new("Mandar", nil, 'mdr', false, false),
          Language.new("Mende", nil, 'men', false, false),
          Language.new("Irish, Middle (900-1200)", nil, 'mga', false, false),
          Language.new("Mi'kmaq", nil, 'mic', false, false),
          Language.new("Minangkabau", nil, 'min', false, false),
          Language.new("Miscellaneous languages", nil, 'mis', false, false),
          Language.new("Mon-Khmer (Other)", nil, 'mkh', false, false),
          Language.new("Malagasy", 'mg', 'mlg', false, false),
          Language.new("Maltese", 'mt', 'mlt', false, false),
          Language.new("Manchu", nil, 'mnc', false, false),
          Language.new("Manipuri", 'ma', 'mni', true, false),
          Language.new("Manobo languages", nil, 'mno', false, false),
          Language.new("Mohawk", nil, 'moh', false, false),
          Language.new("Moldavian", 'mo', 'mol', false, false),
          Language.new("Mongolian", 'mn', 'mon', true, false),
          Language.new("Mossi", nil, 'mos', false, false),
          Language.new("Mirandese", nil, 'mwl', false, false),
          Language.new("Multiple languages", nil, 'mul', false, false),
          Language.new("Munda languages", nil, 'mun', false, false),
          Language.new("Creek", nil, 'mus', false, false),
          Language.new("Marwari", nil, 'mwr', false, false),
          Language.new("Mayan languages", nil, 'myn', false, false),
          Language.new("Erzya", nil, 'myv', false, false),
          Language.new("Nahuatl", nil, 'nah', false, false),
          Language.new("North American Indian", nil, 'nai', false, false),
          Language.new("Neapolitan", nil, 'nap', false, false),
          Language.new("Nauru", 'na', 'nau', false, false),
          Language.new("Navajo", 'nv', 'nav', false, false),
          Language.new("Ndebele, South", 'nr', 'nbl', false, false),
          Language.new("Ndebele, North", 'nd', 'nde', false, false),
          Language.new("Ndonga", 'ng', 'ndo', false, false),
          Language.new("Low German", nil, 'nds', false, false),
          Language.new("Nepali", 'ne', 'nep', false, false),
          Language.new("Nepal Bhasa", nil, 'new', false, false),
          Language.new("Nias", nil, 'nia', false, false),
          Language.new("Niger-Kordofanian (Other)", nil, 'nic', false, false),
          Language.new("Niuean", nil, 'niu', false, false),
          Language.new("Norwegian Nynorsk", 'nn', 'nno', false, false),
          Language.new("Norwegian Bokmal", 'nb', 'nob', false, false),
          Language.new("Nogai", nil, 'nog', false, false),
          Language.new("Norse, Old", nil, 'non', false, false),
          Language.new("Norwegian", 'no', 'nor', true, true),
          Language.new("Northern Sotho", nil, 'nso', false, false),
          Language.new("Nubian languages", nil, 'nub', false, false),
          Language.new("Classical Newari", nil, 'nwc', false, false),
          Language.new("Chichewa", 'ny', 'nya', false, false),
          Language.new("Nyamwezi", nil, 'nym', false, false),
          Language.new("Nyankole", nil, 'nyn', false, false),
          Language.new("Nyoro", nil, 'nyo', false, false),
          Language.new("Nzima", nil, 'nzi', false, false),
          Language.new("Occitan", 'oc', 'oci', true, true),
          Language.new("Ojibwa", 'oj', 'oji', false, false),
          Language.new("Oriya", 'or', 'ori', false, false),
          Language.new("Oromo", 'om', 'orm', false, false),
          Language.new("Osage", nil, 'osa', false, false),
          Language.new("Ossetian", 'os', 'oss', false, false),
          Language.new("Turkish, Ottoman (1500-1928)", nil, 'ota', false, false),
          Language.new("Otomian languages", nil, 'oto', false, false),
          Language.new("Papuan (Other)", nil, 'paa', false, false),
          Language.new("Pangasinan", nil, 'pag', false, false),
          Language.new("Pahlavi", nil, 'pal', false, false),
          Language.new("Pampanga", nil, 'pam', false, false),
          Language.new("Panjabi", 'pa', 'pan', false, false),
          Language.new("Papiamento", nil, 'pap', false, false),
          Language.new("Palauan", nil, 'pau', false, false),
          Language.new("Persian, Old (ca.600-400 B.C.)", nil, 'peo', false, false),
          Language.new("Persian", 'fa', 'per', true, true),
          Language.new("Philippine (Other)", nil, 'phi', false, false),
          Language.new("Phoenician", nil, 'phn', false, false),
          Language.new("Pali", 'pi', 'pli', false, false),
          Language.new("Polish", 'pl', 'pol', true, true),
          Language.new("Pohnpeian", nil, 'pon', false, false),
          Language.new("Portuguese", 'pt', 'por', true, true),
          Language.new("Prakrit languages", nil, 'pra', false, false),
          Language.new("Provençal, Old (to 1500)", nil, 'pro', false, false),
          Language.new("Pushto", 'ps', 'pus', false, false),
          Language.new("Quechua", 'qu', 'que', false, false),
          Language.new("Rajasthani", nil, 'raj', false, false),
          Language.new("Rapanui", nil, 'rap', false, false),
          Language.new("Rarotongan", nil, 'rar', false, false),
          Language.new("Romance (Other)", nil, 'roa', false, false),
          Language.new("Raeto-Romance", 'rm', 'roh', false, false),
          Language.new("Romany", nil, 'rom', false, false),
          Language.new("Rundi", 'rn', 'run', false, false),
          Language.new("Aromanian", nil, 'rup', false, false),
          Language.new("Russian", 'ru', 'rus', true, true),
          Language.new("Sandawe", nil, 'sad', false, false),
          Language.new("Sango", 'sg', 'sag', false, false),
          Language.new("Yakut", nil, 'sah', false, false),
          Language.new("South American Indian (Other)", nil, 'sai', false, false),
          Language.new("Salishan languages", nil, 'sal', false, false),
          Language.new("Samaritan Aramaic", nil, 'sam', false, false),
          Language.new("Sanskrit", 'sa', 'san', false, false),
          Language.new("Sasak", nil, 'sas', false, false),
          Language.new("Santali", nil, 'sat', false, false),
          Language.new("Serbian", 'sr', 'scc', true, true),
          Language.new("Sicilian", nil, 'scn', false, false),
          Language.new("Scots", nil, 'sco', false, false),
          Language.new("Selkup", nil, 'sel', false, false),
          Language.new("Semitic (Other)", nil, 'sem', false, false),
          Language.new("Irish, Old (to 900)", nil, 'sga', false, false),
          Language.new("Sign Languages", nil, 'sgn', false, false),
          Language.new("Shan", nil, 'shn', false, false),
          Language.new("Sidamo", nil, 'sid', false, false),
          Language.new("Sinhalese", 'si', 'sin', true, true),
          Language.new("Siouan languages", nil, 'sio', false, false),
          Language.new("Sino-Tibetan (Other)", nil, 'sit', false, false),
          Language.new("Slavic (Other)", nil, 'sla', false, false),
          Language.new("Slovak", 'sk', 'slo', true, true),
          Language.new("Slovenian", 'sl', 'slv', true, true),
          Language.new("Southern Sami", nil, 'sma', false, false),
          Language.new("Northern Sami", 'se', 'sme', true, false),
          Language.new("Sami languages (Other)", nil, 'smi', false, false),
          Language.new("Lule Sami", nil, 'smj', false, false),
          Language.new("Inari Sami", nil, 'smn', false, false),
          Language.new("Samoan", 'sm', 'smo', false, false),
          Language.new("Skolt Sami", nil, 'sms', false, false),
          Language.new("Shona", 'sn', 'sna', false, false),
          Language.new("Sindhi", 'sd', 'snd', true, false),
          Language.new("Soninke", nil, 'snk', false, false),
          Language.new("Sogdian", nil, 'sog', false, false),
          Language.new("Somali", 'so', 'som', false, false),
          Language.new("Songhai", nil, 'son', false, false),
          Language.new("Sotho, Southern", 'st', 'sot', false, false),
          Language.new("Spanish", 'es', 'spa', true, true),
          Language.new("Sardinian", 'sc', 'srd', false, false),
          Language.new("Serer", nil, 'srr', false, false),
          Language.new("Nilo-Saharan (Other)", nil, 'ssa', false, false),
          Language.new("Swati", 'ss', 'ssw', false, false),
          Language.new("Sukuma", nil, 'suk', false, false),
          Language.new("Sundanese", 'su', 'sun', false, false),
          Language.new("Susu", nil, 'sus', false, false),
          Language.new("Sumerian", nil, 'sux', false, false),
          Language.new("Swahili", 'sw', 'swa', true, false),
          Language.new("Swedish", 'sv', 'swe', true, true),
          Language.new("Syriac", 'sy', 'syr', true, false),
          Language.new("Tahitian", 'ty', 'tah', false, false),
          Language.new("Tai (Other)", nil, 'tai', false, false),
          Language.new("Tamil", 'ta', 'tam', true, false),
          Language.new("Tatar", 'tt', 'tat', false, false),
          Language.new("Telugu", 'te', 'tel', true, false),
          Language.new("Timne", nil, 'tem', false, false),
          Language.new("Tereno", nil, 'ter', false, false),
          Language.new("Tetum", nil, 'tet', false, false),
          Language.new("Tajik", 'tg', 'tgk', false, false),
          Language.new("Tagalog", 'tl', 'tgl', true, true),
          Language.new("Thai", 'th', 'tha', true, true),
          Language.new("Tibetan", 'bo', 'tib', false, false),
          Language.new("Tigre", nil, 'tig', false, false),
          Language.new("Tigrinya", 'ti', 'tir', false, false),
          Language.new("Tiv", nil, 'tiv', false, false),
          Language.new("Tokelau", nil, 'tkl', false, false),
          Language.new("Klingon", nil, 'tlh', false, false),
          Language.new("Tlingit", nil, 'tli', false, false),
          Language.new("Tamashek", nil, 'tmh', false, false),
          Language.new("Tonga (Nyasa)", nil, 'tog', false, false),
          Language.new("Tonga (Tonga Islands)", 'to', 'ton', false, false),
          Language.new("Tok Pisin", nil, 'tpi', false, false),
          Language.new("Tsimshian", nil, 'tsi', false, false),
          Language.new("Tswana", 'tn', 'tsn', false, false),
          Language.new("Tsonga", 'ts', 'tso', false, false),
          Language.new("Turkmen", 'tk', 'tuk', false, false),
          Language.new("Tumbuka", nil, 'tum', false, false),
          Language.new("Tupi languages", nil, 'tup', false, false),
          Language.new("Turkish", 'tr', 'tur', true, true),
          Language.new("Altaic (Other)", nil, 'tut', false, false),
          Language.new("Tuvalu", nil, 'tvl', false, false),
          Language.new("Twi", 'tw', 'twi', false, false),
          Language.new("Tuvinian", nil, 'tyv', false, false),
          Language.new("Udmurt", nil, 'udm', false, false),
          Language.new("Ugaritic", nil, 'uga', false, false),
          Language.new("Uighur", 'ug', 'uig', false, false),
          Language.new("Ukrainian", 'uk', 'ukr', true, true),
          Language.new("Umbundu", nil, 'umb', false, false),
          Language.new("Undetermined", nil, 'und', false, false),
          Language.new("Urdu", 'ur', 'urd', true, false),
          Language.new("Uzbek", 'uz', 'uzb', false, true),
          Language.new("Vai", nil, 'vai', false, false),
          Language.new("Venda", 've', 'ven', false, false),
          Language.new("Vietnamese", 'vi', 'vie', true, true),
          Language.new("Volapük", 'vo', 'vol', false, false),
          Language.new("Votic", nil, 'vot', false, false),
          Language.new("Wakashan languages", nil, 'wak', false, false),
          Language.new("Walamo", nil, 'wal', false, false),
          Language.new("Waray", nil, 'war', false, false),
          Language.new("Washo", nil, 'was', false, false),
          Language.new("Welsh", 'cy', 'wel', false, false),
          Language.new("Sorbian languages", nil, 'wen', false, false),
          Language.new("Walloon", 'wa', 'wln', false, false),
          Language.new("Wolof", 'wo', 'wol', false, false),
          Language.new("Kalmyk", nil, 'xal', false, false),
          Language.new("Xhosa", 'xh', 'xho', false, false),
          Language.new("Yao", nil, 'yao', false, false),
          Language.new("Yapese", nil, 'yap', false, false),
          Language.new("Yiddish", 'yi', 'yid', false, false),
          Language.new("Yoruba", 'yo', 'yor', false, false),
          Language.new("Yupik languages", nil, 'ypk', false, false),
          Language.new("Zapotec", nil, 'zap', false, false),
          Language.new("Zenaga", nil, 'zen', false, false),
          Language.new("Zhuang", 'za', 'zha', false, false),
          Language.new("Zande", nil, 'znd', false, false),
          Language.new("Zulu", 'zu', 'zul', false, false),
          Language.new("Zuni", nil, 'zun', false, false),
          Language.new("Romanian", 'ro', 'rum', true, true),
          Language.new("Portuguese (BR)", 'pb', 'pob', true, true),
          Language.new("Montenegrin", 'me', 'mne', true, false),
          Language.new("Chinese (traditional)", 'zt', 'zht', true, true),
          Language.new("Chinese bilingual", 'ze', 'zhe', true, false),
          Language.new("Portuguese (MZ)", 'pm', 'pom', true, false),
          Language.new("Extremaduran", 'ex', 'ext', true, false)
      ]
    end
  end
end


